[[plugins]]
repo = 'Shougo/unite.vim'
hook_post_source = '''
"Uniteの設定"{{{
""""""""""""""""""""""""""""""
  "基本的な設定
  let g:unite_source_file_mru_long_limit = 3000
  let g:unite_source_directory_mru_long_limit = 3000
  let g:unite_source_file_mru_limit = 250
  let g:unite_enable_start_insert = 1
  let g:unite_enable_ignore_case = 1
  let g:unite_enable_smart_case = 1
  let g:unite_source_history_yank_enable = 1
  "let g:unite_source_rec_max_cache_files = 50000
  "call unite#filters#matcher_default#use(['matcher_fuzzy'])
[[plugins]]
  repo = 'Shougo/vimfiler'
  hook_source = '''
  "{{{
  """"""""""""""""""""""""""""""
  let g:vimfiler_as_default_explorer = 1
  let g:vimfiler_ignore_pattern='\(^\.\|\~$\|\.pyc$\|\.[oad]$\)'

  "この変数はexecute_vimfiler_associated(enterにmapping)で何をするかコントロールする。
  let g:vimfiler_execute_file_list = {}
  let g:vimfiler_execute_file_list = {
    \ "_" : "vim",
    \ "xlsx" : "open",
    \ "xlam" : "open",
    \ "xlsm" : "open"}

  " call vimfiler#custom#profile('default', 'context', {
  "      \ 'quit' : 0,
  "      \ 'safe' : 0,
  "      \ 'winwidth' : 35,
  "      \ 'toggle' : 1,
  "      \ 'simple' : 0,
  "      \ 'split' : 1,
  "      \ })
  "
  call vimfiler#custom#profile('default', 'context', {
       \ 'safe' : 0,
       \ 'toggle' : 0,
       \ 'simple' : 0,
       \ 'split' : 0,
       \ 'quit' : 1,
       \ })

  nnoremap <leader>f :<C-u>VimFilerBufferDir<CR>
  nnoremap <leader>F :<C-u>VimFiler -nosimple<CR>

  " vimfiler上でのキーマッピング
  autocmd MyAutoCmd FileType vimfiler call s:vimfiler_my_settings()
  function! s:vimfiler_my_settings()
    "タブ移動,historyとかをつぶしている。
    nmap <silent><buffer> t [tag]
    nnoremap <silent><buffer> [tag]n :TABNEW<CR>
    nnoremap <silent><buffer> [tag]h :tabprevious<CR>
    nnoremap <silent><buffer> [tag]l :tabnext<CR>
    nnoremap <silent><buffer> [tag]q :tabclose<CR>
    nmap <silent><buffer> <c-r> <plug>(vimfiler_redraw_screen)
    "その他
    nmap <silent><buffer> <A-Up> <Plug>(vimfiler_smart_h)
    nmap <silent><buffer> f <Plug>(vimfiler_toggle_mark_current_line)
    nmap <silent><buffer> i <Plug>(vimfiler_choose_action)
    nmap <silent><buffer> F <Plug>(vimfiler_toggle_mark_all_lines)
    nmap <silent><buffer> vs <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_popup_shell)
    nmap <silent><buffer> <C-CR> <Plug>(vimfiler_choose_action)tabopen<cr>
    nmap <silent><buffer> du <Plug>(vimfiler_switch_to_another_vimfiler)

    nmap <buffer><expr> <CR> vimfiler#smart_cursor_map(
          \  "\<Plug>(vimfiler_cd_file)",
          \  "\<Plug>(vimfiler_edit_file)")

    nmap <buffer> yy
    \ <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_clipboard_copy_file)
    nmap <buffer> p
    \ <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_clipboard_paste)
    nmap <buffer> m
    \ <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_clipboard_move_file)

  endfunction

  "}}}
  '''
  on_event = "VimEnter"
  depends = ['unite.vim']
